# Generated by Django 5.1.2 on 2025-01-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_main', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
