# Generated by Django 5.1.2 on 2025-01-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_main', '0005_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
