# Generated by Django 5.1.2 on 2025-08-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_main', '0015_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
