# Generated by Django 5.1.2 on 2025-08-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_main', '0019_conversation_message_messagereadstatus'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='instagram_m_convers_cf9635_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='instagram_m_sender__6b489c_idx'),
        ),
    ]
