# Generated by Django 5.1.2 on 2025-09-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_main', '0022_gender_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
